target:
  _target_: torch.optim.AdamW
  #lr: 1e-3
  lr: 1e-3
  weight_decay: 1e-4
  betas: [0.9, 0.95]

extras:
  train_batch_size: ${data.loaders.train.batch_size}
  layer_decay: 0.75
  decay_type: right
  ema: 
    - 0.996
    - 1.0
  ipe_scale: 1.0


