defaults:
  - map.yaml

additional:
  AUROC: 
    _target_: torchmetrics.AUROC
    task: "multilabel"
    num_labels: ${data.dataset.num_classes}
    average: "macro"
    thresholds: null
  T1ACC:
    _target_: birdset.modules.metrics.multilabel.TopKAccuracy
    topk: 1