default_root_dir: ${paths.output_dir}
min_epochs: 1
max_epochs: 60

accelerator: gpu
devices: 2
enable_checkpointing: False
enable_model_summary: False
enable_progress_bar: True

num_sanity_val_steps: 0
limit_val_batches: 1.0
#limit_val_batches: 0
barebones: False
check_val_every_n_epoch: 5

strategy: auto
deterministic: False

gradient_clip_val: null
accumulate_grad_batches: 1
#precision: 16
precision: bf16