default_root_dir: ${paths.output_dir}
min_epochs: 1
max_epochs: 10

accelerator: cpu
devices: 1
enable_checkpointing: True
enable_model_summary: True
enable_progress_bar: True

strategy: auto
deterministic: False

gradient_clip_val: 0.5
accumulate_grad_batches: 3
precision: 16