default_root_dir: ${paths.output_dir}
min_epochs: 1
max_epochs: 10

accelerator: gpu
devices: 1
enable_checkpointing: False
enable_model_summary: True
enable_progress_bar: True

num_sanity_val_steps: 0
limit_val_batches: 0
barebones: False

strategy: auto
deterministic: False

gradient_clip_val: 0.5
accumulate_grad_batches: 3
precision: 16