  _target_: pytorch_lightning.loggers.mlflow.MLFlowLogger
  experiment_name: "test"
  run_name: ${task_name}_${data.dataset.name}_${start_time}
  tracking_uri: ${paths.log_dir}/mlflow/mlruns # run `mlflow ui` command inside the `logs/mlflow/` dir to open the UI
  tags: null
  # save_dir: "./mlruns"
  prefix: ""
  artifact_location: null
  # run_id: ""