name: AudioMAE
norm_layer: nn.LayerNorm
norm_pix_loss: True
sampling_rate: 32_000
mask_ratio: 0.8
encoder:
    img_size_x: ${data.dataset.target_length}
    img_size_y: 128
    patch_size: 16
    in_chans: 1
    embed_dim: 768
    depth: 12
    num_heads: 12
    pos_trainable: false
    mlp_ratio: 4
decoder:
    mode: swinv2
    embed_dim: 512
    depth: 12
    num_heads: 16
    mlp_ratio: 4
    pos_trainable: false 
    patch_size: 16
    no_shift: false

