
name: AudioMAE
norm_layer: nn.LayerNorm
norm_pix_loss: True
sampling_rate: 32_000
encoder:
    img_size_x: ${data.dataset.target_length}
    img_size_y: 128
    patch_size: 16
    in_chans: 1
    embed_dim: 1024
    depth: 24
    num_heads: 16
    pos_trainable: False
    mlp_ratio: 4
decoder:
    decoder_mode: "swin"
    embed_dim: 512
    depth: 8
    num_heads: 16
    mlp_ratio: 4
    pos_trainable: False 
    mode: 0
    patch_size: 16

