name: AudioMAE_FT
norm_layer: nn.LayerNorm
sampling_rate: 32_000
encoder:
    img_size_x: ${data.transform.target_length}
    img_size_y: 128
    patch_size: 16
    in_chans: 1
    embed_dim: 768
    depth: 12
    num_heads: 12
    pos_trainable: False
    mlp_ratio: 4