name: VIT
norm_layer: nn.LayerNorm
sampling_rate: 32_000
img_size_x: ${data.dataset.target_length}
img_size_y: 128
patch_size: 16
in_chans: 1
embed_dim: 1024
global_pool: True
mlp_ratio: 4
qkv_bias: True
eps: 1e-6
num_heads: 16
depth: 24
drop_path: 0.1
num_classes: ${data.dataset.num_classes} 
pos_trainable: False
pretrained_weights_path: /home/lrauch/AudioMAE_XCL_epo20_no10nomixupxup_l_swin.ckpt
#pretrained_weights_path: /home/lrauch/AudioMAE_XCL_epo20_nomixup_l_swin.ckpt
#pretrained_weights_path: /home/lrauch/AudioMAE_XCL_epoch=30_mixup0.7_l_swin.ckpt
#pretrained_weights_path: /home/lrauch/AudioMAE_XCL_epoch=99_mixup_l.ckpt
#pretrained_weights_path: /home/lrauch/AudioMAE_XCL_epoch=99_mixu0.5mixup_l.ckpt
target_length: ${data.dataset.target_length}
mask2d: ${data.transform.mask2d}
mask_t_prob: ${data.transform.mask_t_prob}
mask_f_prob: ${data.transform.mask_f_prob}
freeze_backbone: false