name: VIT
norm_layer: nn.LayerNorm
sampling_rate: 32_000
img_size_x: ${data.dataset.target_length}
img_size_y: 128
patch_size: 16
in_chans: 1
embed_dim: 768
global_pool: True
mlp_ratio: 4
qkv_bias: True
eps: 1e-6
num_heads: 12
depth: 12
drop_path: 0.1
num_classes: ${data.dataset.num_classes} 
pos_trainable: False
#pretrained_weights_path: null
#pretrained_weights_path: /home/lrauch/mnt_check/pretrain_xcl/runs/XCL/AudioMAE/2024-11-11_204649/callback_checkpoints/AudioMAE_XCL_epoch=64.ckpt
#pretrained_weights_path: /home/lrauch/mnt_check/pretrain_xcl/runs/XCL/AudioMAE/2024-11-11_204649/callback_checkpoints/AudioMAE_XCL_epoch=74.ckpt
#pretrained_weights_path: /home/lrauch/AudioMAE_XCL_epoch=74.ckpt
pretrained_weights_path: /home/lrauch/AudioMAE_XCL_epoch=64.ckpt

#pretrained_weights_path: ${paths.root_dir}/weights/amae_as2m_pretrained.pth
#pretrained_weights_path: ${paths.root_dir}/logs/pretrain_xcm/runs/XCM/AudioMAE/2024-11-04_225700/epoch=79-step=230720.ckpt
#pretrained_weights_path: ${paths.root_dir}/logs/pretrain_asb/runs/audioset_balanced/AudioMAE/2024-10-23_151304/callback_checkpoints/AudioMAE_audioset_balanced_epoch=79.ckpt
target_length: ${data.dataset.target_length}
mask2d: ${data.transform.mask2d}
mask_t_prob: ${data.transform.mask_t_prob}
mask_f_prob: ${data.transform.mask_f_prob}
