# @package _global_
defaults:
  - _self_
  - callbacks: default
  - data/dataset: esc50
  - data/loaders: default
  - data/transform: melscale
  - logger: mlflow
  - hydra: workstation
  - module/network: vit_base_16
  - module/optimizer: adamw
  - module/scheduler: cosine
  - module/loss: label_smoothing_cross_entropy
  - paths: workstation
  - trainer: single_gpu
  - experiment: null
  
seed: 42
start_time: ${now:%Y-%m-%d_%H%M%S}
task_name: "finetune"
 
